### ISSUE TITLE
create automated installer

### ISSUE THREAD

**Issue by derStephan** [agendav/agendav#194]
Hi, I just tried to walk through the ridiculously complicated installation procedure given in the documentation. 

Honestly, I have to **manually** create a settings.php, then I have to **manually** create a directory and an SQLite-file, then I need to run something on the command line? No offence but you have got to be kidding me and everybody around here. Where is the command line interface on my shared hoster?

What's the problem with creating a settings.php-file from a PHP script? Same applies to an SQLite-file and all other steps described in the documentation. Putting all these steps together in a simple installation script should not be harder than writing all that stuff into the documentation.

It is just sad that you put a lot of effort in this but do not provide a simple way of installing or upgrading. This renders the whole project pretty useless for the vast majority of users out there.

**Comment by mmoll** [comment]
I really do disagree here for a whole bunch of reasons. While the installation could for sure be made easier with some wizard-like workflow, having something like PHP hosting with FTP acesss and no shell available is tricking users with no knowledge of system/application adminstration knowledge into running apps they can not properly care for, often leading to widely open security holes.

**Comment by derStephan** [comment]
Thanks for your reply. 

>having something like PHP hosting with FTP acesss and no shell available is tricking users with no knowledge of system/application adminstration knowledge into running apps 

In the contrary. The great majority of users out there are running things on hosted servers. Now you are saying, that all of those users are total morons when it comes to security? And you are telling me, that the people of Wordpress or Owncloud or Baikal doing it wrong because they provide, what I request? Interesting. 

>running apps they can not properly care for, often leading to widely open security holes.

Which security holes would that be? On a shared hoster, PHP and MySQL are maintained by the hoster, so no unfixed security holes there. The only thing with possible security holes here is agendav. 

And the more complicated it is to update your software the less frequently the updates will be applied. Have you read what is to be done to upgrade from 1.x to 2.0? 

If the installation would be just like klicking a button, there would be no such thing as old/unsecure versions of your program. Just ask yourself why all of those popular programs out there have easy installers and even easier upgrade routines.

**Comment by mmoll** [comment]
> In the contrary. The great majority of users out there are running things on hosted servers. Now you are saying, that all of those users are total morons when it comes to security?

No. but I'm saying that running applications on the internet is something entirely different than, let's say playing a CD on a home stereo system.

> And you are telling me, that the people of Wordpress or Owncloud or Baikal doing it wrong because they provide, what I request?

Again, I do say that a one-click installer is a fine thing, but I also do clearly say it just can not solve specific problems that often come along as consequence of running an internet-facing web applications.

"The people" in case of agendav is more or less exactly one person, doing all that in his spare time, please keep that in mind. As it's open source, anybody could create and pull request a one-click installer/updater. I know if's pretty hefty to return a feature request with something that could get understood easily as "do my work or shut up otherwise", but this is open source reality. Baikal also has the same problem with features/fixes, as there's (unlike Wordpress or Owncloud) no huge developer community and/or a company that is paying developer work.

> And the more complicated it is to update your software the less frequently the updates will be applied. 

All the applications you're mentioned do show pretty well that a lot of people do not touch their running apps, once they managed to get these installed and there are sometimes problems with upgrades also there. Usually things teand to utterly break in such settings, after the hoster updated PHP to a new release and people are clueless then, how to get things going again.

> Have you read what is to be done to upgrade from 1.x to 2.0?

I did that exact upgrade from 1.2.6 to 2.x and had no problems, following the docs.

> If the installation would be just like klicking a button, there would be no such thing as old/unsecure versions of your program

I can say that especially updating and data migrations of database contents can be tricky and as there are a lot of different configurations in the wild, see #188 for a very simple example. Frameworks like Doctrine (also used by agendav 2.x) do help with that, but there's still some dark matter around, leading to problems, especailly if there's no big integrative testing of upgrades with all database types (which would need to be created by developers first) or a big community, willing to play guinea pigs by running development versions.

**Comment by derStephan** [comment]
Please don't get me wrong, I really appreciate all effort done here. 

>Again, I do say that a one-click installer is a fine thing, but I also do clearly say it just can not solve specific problems that often come along as consequence of running an internet-facing web applications.

Funny to say something like that in conjunction with a PHP-driven webapplication. 

>All the applications you're mentioned do show pretty well that a lot of people do not touch their running apps, once they managed to get these installed 

I do agree but the same applies for all those spare time administrators running some "rent-a-server" setting. I really believe, that 90% of such "rent-a-server" users have no clue how to maintain such a machine. When it comes to security, I'd prefer some professional hosting over self-maintained servers. 

My point is that the probability of doing upgrades often is rising with ease of the upgrade process. 

>Frameworks like 

:-) I already looked into the vendor directory which looks like a who-is-who of all fancy webtools out there. 

Again: no offence, pal. I just wanted to ask for something to get stuff running at all. Thanks to all of you for all your work. Maybe Abodo wil find some time to help out.

**Comment by derStephan** [comment]
@pixelbrackets 

May I ask, why this is closed?
